version: '3.7'

services:
    nginx_testcase:
        container_name: nginx_testcase
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "99:99"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www/html:z
        depends_on:
            - php_testcase
        networks:
            - project_testcase

    php_testcase:
        container_name: php_testcase
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/html:z
        depends_on:
            pgsql_testcase:
                condition: service_healthy
        networks:
            - project_testcase

    pgsql_testcase:
        container_name: pgsql_testcase
        image: postgres:10.1
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/testcase"
        ports:
            - "5432:5432"
        volumes:
            - ./docker/provision/pgsql/init:/docker-entrypoint-initdb.d
            - pgsql_testcase:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U testcase -d testcase"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - project_testcase

networks:
    project_testcase:
        driver: bridge

volumes:
    pgsql_testcase:
        driver: local
